bbox_color: [150, 0, 0]
bbox_thickness: 3

bbox_labelstr:
  font_size: 1
  font_thickness: 2
  offset_x: 0
  offset_y: -15

loading_bar_color: [0, 0, 255]
loading_bar_radious: [40, 40]
loading_bar_labelstr:
  font_thickness: 7
  max_count_frame: 50



kpt_color_map:
  0:
    name: Nose
    color: [0, 0, 255]
    radius: 6
  1:
    name: Right Eye
    color: [255, 0, 0]
    radius: 6
  2:
    name: Left Eye
    color: [255, 0, 0]
    radius: 6
  3:
    name: Right Ear
    color: [0, 255, 0]
    radius: 6
  4:
    name: Left Ear
    color: [0, 255, 0]
    radius: 6
  5:
    name: Right Shoulder
    color: [193, 182, 255]
    radius: 6
  6:
    name: Left Shoulder
    color: [193, 182, 255]
    radius: 6
  7:
    name: Right Elbow
    color: [16, 144, 247]
    radius: 6
  8:
    name: Left Elbow
    color: [16, 144, 247]
    radius: 6
  9:
    name: Right Wrist
    color: [1, 240, 255]
    radius: 6
  10:
    name: Left Wrist
    color: [1, 240, 255]
    radius: 6
  11:
    name: Right Hip
    color: [140, 47, 240]
    radius: 6
  12:
    name: Left Hip
    color: [140, 47, 240]
    radius: 6
  13:
    name: Right Knee
    color: [223, 155, 60]
    radius: 6
  14:
    name: Left Knee
    color: [223, 155, 60]
    radius: 6
  15:
    name: Right Ankle
    color: [139, 0, 0]
    radius: 6
  16:
    name: Left Ankle
    color: [139, 0, 0]
    radius: 6

kpt_labelstr:
  font_size: 0.5
  font_thickness: 1
  offset_x: 10
  offset_y: 0


skeleton_map:
  - srt_kpt_id: 15
    dst_kpt_id: 13
    color: [0, 100, 255]
    thickness: 2
  - srt_kpt_id: 13
    dst_kpt_id: 11
    color: [0, 255, 0]
    thickness: 2
  - srt_kpt_id: 16
    dst_kpt_id: 14
    color: [255, 0, 0]
    thickness: 2
  - srt_kpt_id: 14
    dst_kpt_id: 12
    color: [0, 0, 255]
    thickness: 2
  - srt_kpt_id: 11
    dst_kpt_id: 12
    color: [122, 160, 255]
    thickness: 2
  - srt_kpt_id: 5
    dst_kpt_id: 11
    color: [139, 0, 139]
    thickness: 2
  - srt_kpt_id: 6
    dst_kpt_id: 12
    color: [237, 149, 100]
    thickness: 2
  - srt_kpt_id: 5
    dst_kpt_id: 6
    color: [152, 251, 152]
    thickness: 2
  - srt_kpt_id: 5
    dst_kpt_id: 7
    color: [148, 0, 69]
    thickness: 2
  - srt_kpt_id: 6
    dst_kpt_id: 8
    color: [0, 75, 255]
    thickness: 2
  - srt_kpt_id: 7
    dst_kpt_id: 9
    color: [56, 230, 25]
    thickness: 2
  - srt_kpt_id: 8
    dst_kpt_id: 10
    color: [0, 240, 240]
    thickness: 2
  - srt_kpt_id: 1
    dst_kpt_id: 2
    color: [224, 255, 255]
    thickness: 2
  - srt_kpt_id: 0
    dst_kpt_id: 1
    color: [47, 255, 173]
    thickness: 2
  - srt_kpt_id: 0
    dst_kpt_id: 2
    color: [203, 192, 255]
    thickness: 2
  - srt_kpt_id: 1
    dst_kpt_id: 3
    color: [196, 75, 255]
    thickness: 2
  - srt_kpt_id: 2
    dst_kpt_id: 4
    color: [86, 0, 25]
    thickness: 2
  - srt_kpt_id: 3
    dst_kpt_id: 5
    color: [255, 255, 0]
    thickness: 2
  - srt_kpt_id: 4
    dst_kpt_id: 6
    color: [255, 18, 200]
    thickness: 2

cooking_roi: [0.6427, 0.6389, 0.7656, 0.6528, 0.7651, 0.8463, 0.6385, 0.8333]

pre_state: preparing
high_confidence_count: 0
difference_count: 0
inside_and_interact_count: 0